# Numpy Array vs Python Lists

In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [3]:
%timeit [j**4 for j in range(1,9)]

2.61 µs ± 79.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
import numpy as np
%timeit np.arange(1,9)**4

6.38 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Numpy Array

In [5]:
import numpy as np

x = [1,2,3,4,5]

y = np.array(x)

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
lis = []

for i in range(1,5):
    int_1 = int(input("Enter Value:-"))
    lis.append(int_1)
    
print(np.array(lis))


Enter Value:-5
Enter Value:-4
Enter Value:-3
Enter Value:-2
[5 4 3 2]


In [8]:
ar2 = np.array([[1,2,23,3],[1,2,34,4]])
print(ar2)
print(ar2.ndim)

[[ 1  2 23  3]
 [ 1  2 34  4]]
2


In [9]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [10]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [7]:
import numpy as np

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [15]:
ar_one = np.ones(4)

print(ar_one)

[1. 1. 1. 1.]


# Empty

In [16]:
ar_em = np.empty(4)

print(ar_em)   

[1. 1. 1. 1.]


# Range

In [17]:
ar_rn = np.arange(4)

print(ar_rn)

[0 1 2 3]


# Diagonal

In [25]:
ar_dia = np.eye(3,3)

print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# linspace

In [32]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Random

## rand( )

In [39]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.19810553 0.84017131 0.6905678  0.07717724]


In [40]:
var1 = np.random.rand(2,5)

print(var1)

[[0.78754943 0.98601459 0.25100092 0.31378338 0.29055194]
 [0.65989232 0.93077373 0.00846629 0.22744706 0.68720544]]


## randn( )


In [41]:
var2 = np.random.randn(5)

print(var2)

[-0.68223591  1.14793962  0.41923643 -0.99622903 -0.60489869]


## ranf( )

In [38]:
var3 =np.random.ranf(5)

print(var3)

[0.50010461 0.11066068 0.63164236 0.4827937  0.23581551]


## randint( )

In [45]:
# var4 = np.random.randint(min,max,total_value)

var4 = np.random.randint(5,20,5)

print(var4)

[15 15 10 18 18]
