# Numpy Array vs Python Lists

In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [3]:
%timeit [j**4 for j in range(1,9)]

2.61 µs ± 79.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
import numpy as np
%timeit np.arange(1,9)**4

6.38 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Numpy Array

In [5]:
import numpy as np

x = [1,2,3,4,5]

y = np.array(x)

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
lis = []

for i in range(1,5):
    int_1 = int(input("Enter Value:-"))
    lis.append(int_1)
    
print(np.array(lis))


Enter Value:-5
Enter Value:-4
Enter Value:-3
Enter Value:-2
[5 4 3 2]


In [8]:
ar2 = np.array([[1,2,23,3],[1,2,34,4]])
print(ar2)
print(ar2.ndim)

[[ 1  2 23  3]
 [ 1  2 34  4]]
2


In [9]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [10]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
